TP1/Controllers/EmpresaController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP1.Models;

namespace TP1.Controllers
{
    [Authorize]
    public class EmpresaController : Controller
    {
        private TP1Context context;

        public EmpresaController()
        {
            context = new TP1Context();
        }

        // GET: Empresas
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListasEmpresas()
        {
            var emp = context.Empresas.Include("ApplicationUser").OrderBy(x =>x.Nome);
            return View(context.Empresas);
        }

     

        [HttpGet]
      //  [Authorize(Roles = "Empresa")]
        public ActionResult PreenchePerfil()
        {
            //   ViewBag.Perfis = new SelectList(context.Roles.Where(u => !u.Name.Contains("Admin")).ToList(), "Name", "Name");
            return View();
        }

        [HttpPost]
      //  [Authorize(Roles = "Empresa")]
        public ActionResult PreenchePerfil(Empresa a)
        {
            var CurrentID = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                Empresa f = context.Empresas.Single(x => x.UserId == CurrentID);

                f.Nome = a.Nome;
                f.Telefone = a.Telefone;
                f.Propostas = null;

            }
            context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

TP1/Controllers/PropostaController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP1.Models;

namespace TP1.Controllers
{
    public class PropostaController : Controller
    {
        private TP1Context context;

        public PropostaController()
        {
            context = new TP1Context();
        }

        // GET: Propostas
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        //  [Authorize(Roles = "Empresa")]
        public ActionResult SubmitE()
        {
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "Empresa")]
        public ActionResult SubmitE(Proposta s)
        {
            var CurrentID = User.Identity.GetUserId();
            Empresa emp = context.Empresas.Single(x => x.UserId == CurrentID);
            if (ModelState.IsValid)
            {
                if (emp.Nome == null)
                {
                    return RedirectToAction("../Home/PerfilIncompleto");
                }

                s.Livre = true;
                s.Student = null;
                s.Empresas = emp;
                emp.Propostas.Add(s);
            }
            context.SaveChanges();
            return RedirectToAction("../Home/Submetido");
        }


        public ActionResult ListaPropostas()
        {
            var CurrentID = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                if (User.IsInRole("Empresa"))
                {
                    Empresa emp = context.Empresas.Include("Propostas").Single(x => x.UserId == CurrentID);
                    if (emp.Propostas.Count == 0)
                        return View("NoPropostas");
                    return View(emp.Propostas);
                }
                else
                {
                    if (User.IsInRole("Docente"))
                    {
                        Docente doc = context.Docentes.Include("Propostas").Single(x => x.UserId == CurrentID);
                        if (doc.Propostas.Count == 0)
                            return View("NoPropostas");
                        return View(doc.Propostas);
                    }
                    else
                    {
                        if (User.IsInRole("Aluno"))
                        {
                            return View(context.Propostas);
                        }
                    }
                }
            }
            return View(context.Propostas);
        }

        public ActionResult ListaPropostasEmp(int id)
        {

            Empresa emp = context.Empresas.Include("Propostas").Single(x => x.ID == id);
            if (emp.Propostas.Count == 0)
                return View("NoPropostas");
            return View(emp.Propostas);
        }

        [HttpGet]
        [Authorize(Roles = "Docente")]
        [Authorize(Roles = "Comissao")]
        public ActionResult SubmitP()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Docente")]
        [Authorize(Roles = "Comissao")]
        public ActionResult SubmitP(Proposta s, int orientadores)
        {
            var CurrentID = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                Docente doc = context.Docentes.Single(x => x.UserId == CurrentID);
                if (doc.Nome == null)
                {
                    return RedirectToAction("Home/PerfilIncompleto");
                }

                s.Livre = true;
                s.Student = null;

                if (doc.Nome != null)
                    doc.Propostas.Add(s);
            }
            context.SaveChanges();
            return RedirectToAction("Home/Submetido");
        }

        public ActionResult NoPropostas()
        {
            return View();
        }

        public ActionResult EscolherOri(int num)
        {

            context.SaveChanges();
            return RedirectToAction("Home/Submetido");
        }
    }
}

TP1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Estágios@DEIS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Estágios@DEIS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Início", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Ver Estágios", "ListaPropostas", "Proposta")</li>
                    @*<li>@Html.ActionLink("Ver Empresas", "ListasEmpresas", "Empresas")</li>
        <li>@Html.ActionLink("Ver Docentes", "ListasDocentes", "Docentes")</li>*@    @*isto eventualmente sai daqui*@

                @if (User.IsInRole("Aluno"))
                {
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">Listar<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Estágios", "ListaPropostas", "Proposta")</li>
                            <li>@Html.ActionLink("Empresas", "ListasEmpresas", "Empresa")</li>

                        </ul>
                    </li>
                    <li> @Html.ActionLink("Submeter Candidatura", "Candidatar", "Aluno")</li>
                    <li> @Html.ActionLink("Editar Perfil", "PreenchePerfil", "Aluno")</li>
                }

                @if (User.IsInRole("Empresa"))
                {
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">Listar<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Estágios", "ListaPropostas", "Proposta")</li>
                        </ul>
                    </li>
                    <li> @Html.ActionLink("Submeter Estágio", "SubmitE", "Proposta")</li>
                    <li> @Html.ActionLink("Editar Perfil", "PreenchePerfil", "Empresa")</li>
                }
                @if (User.IsInRole("Admin"))
                {
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">Comissão de curso<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Listar membros", "listComissaoCurso", "Admin")</li>
                            <li>@Html.ActionLink("Editar membros", "chooseMemberToEdit", "Admin")</li>
                        </ul>

                    </li>
                }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>



    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <b>Estágios@DEIS</b> por Ana Rita Câmara e Bernardo Vitória</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>